# To activate environment: source .venv/bin/activate  

# Twitter Developer Credentials
API_KEY = 'j8zql5uWNYZzPT8KhdBQQo5IY'
API_SECRET = 'gpJWRfB3CQlQkkQP2mWlkw7skYdxh7ced5Ttv3crAFxJr8ZJnW'
ACCESS_TOKEN = '1477420259644776452-LPNEkN5VhSgJ5D9kUyCv1hjwOrxOXp'
ACCESS_TOKEN_SECRET = 'HaNqrGY6P0wF8RAIGJD2TFycdZeCm95uLhSV35pRPvlkH'
BEARER_TOKEN = 'AAAAAAAAAAAAAAAAAAAAAOvYqwEAAAAAlgsPSya1m%2FfDVSs%2B%2BwtuRxo0DjY%3D9zf2IIFgALTJoKX9VELLyOahrHvo9obrce245Q2TllcIIExnxQ'
CLIENT_ID = 'UUYwMmtTaW1YMWs4dnpuM1lwQXo6MTpjaQ'
CLIENT_SECRET = 'sDVwzvWDcs_X_JmndX2d8ia4Kh-W_vZyhdNux13BJ275TEsLDQ'

# Snowflake Credentials
SNOWFLAKE_USER = 'melissamullen'
SNOWFLAKE_PASSWORD = '4499569Joy!'
SNOWFLAKE_ACCOUNT  = 'lhb14091.us-east-1'
SNOWFLAKE_WAREHOUSE = 'melissa_warehouse_xs'
SNOWFLAKE_DATABASE = 'melissa_db'
SNOWFLAKE_SCHEMA = 'melissa_schema'